categorias = [
    "Salario",
    "Ingresos por freelance/trabajo independiente",
    "Ingresos por alquiler de propiedad",
    "Ingresos por inversiones",
    "Reembolsos",
    "Bonificaciones",
    "Regalos",
    "Otros ingresos",
    "Vivienda",
    "Alimentación",
    "Transporte",
    "Servicios públicos",
    "Salud",
    "Entretenimiento",
    "Educación",
    "Ahorros e inversiones",
    "Ropa y accesorios",
    "Cuidado personal",
    "Viajes y vacaciones",
    "Donaciones y caridad",
    "Deudas",
    "Seguros",
    "Impuestos"
]